alter session set nls_date_format='yyyy/mm/dd hh24:mi:ss'
/

/* CHG-14038 : Create weekly job to clean up temp tables generated by reports */
begin
    dbms_scheduler.create_job (
        job_name        => 'cleanup_temp_tables_job',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'begin gx_support.cleanup_temp_tables; end;',
        start_date      => systimestamp,
        repeat_interval => 'freq=weekly; byday=sun; byhour=12; byminute=0; bysecond=0;',
        enabled         => true,
        comments        => 'Clean up temp table created by MicroStrategy.');

end;
/

set line      180
set pagesize  80
col owner     format a15
col job_name  format a35
col job_class format a20
col start_date      format a40
col repeat_interval format a50

SELECT owner, job_name, job_class, enabled, START_DATE, REPEAT_INTERVAL FROM dba_scheduler_jobs
/

