rem
rem Install database objects
rem

Rem Tables for utlpurge script

CREATE TABLE UTL$LIST_TREE_NODES (
  NODE#             NUMBER NOT NULL PRIMARY KEY, 
  OWNER             VARCHAR2(30) NOT NULL,
  TABLE_NAME        VARCHAR2(30) NOT NULL,
  PRIMARY_KEY_TABLE VARCHAR2(30))
/


CREATE TABLE UTL$LOG (
  LOG#          NUMBER NOT NULL PRIMARY KEY,
  DATETIME      DATE   NOT NULL,
  TASK          VARCHAR2(10),
  CALLER        VARCHAR2(50),
  MESSAGE       VARCHAR2(500))
/

CREATE TABLE UTL$SQL (
  LOG#          NUMBER NOT NULL PRIMARY KEY,
  DATETIME      DATE   NOT NULL,
  CALLER        VARCHAR2(30),
  SQL_TEXT      VARCHAR2(4000))
/



CREATE TABLE UTL$INDEXES (
  OWNER           VARCHAR2(30) NOT NULL,
  INDEX_NAME      VARCHAR2(30) NOT NULL,
  INDEX_TYPE      VARCHAR2(27),
  TABLE_OWNER     VARCHAR2(30) NOT NULL,
  TABLE_NAME      VARCHAR2(30) NOT NULL,
  UNIQUENESS      VARCHAR2(9),
  COLUMN_NAMES         VARCHAR2(4000),
  TABLESPACE_NAME VARCHAR2(30),
PRIMARY KEY(OWNER, INDEX_NAME)
)
/

CREATE TABLE UTL$TABLES (
  OWNER            VARCHAR2(30) NOT NULL,
  TABLE_NAME       VARCHAR2(30) NOT NULL,
  TEMP_TABLE_NAME  VARCHAR2(30) NOT NULL,
PRIMARY KEY(OWNER,TABLE_NAME)  
)
/

CREATE TABLE UTL$CONSTRAINTS (
  OWNER               VARCHAR2(30) NOT NULL,
  CONSTRAINT_NAME     VARCHAR2(30) NOT NULL,
  CONSTRAINT_TYPE     VARCHAR2(1),
  TABLE_NAME          VARCHAR2(30) NOT NULL,
  SEARCH_CONDITION    LONG,
  R_OWNER             VARCHAR2(30),
  R_CONSTRAINT_NAME   VARCHAR2(30),
  R_TABLE_NAME        VARCHAR2(30),
  COLUMN_NAMES        VARCHAR2(4000),
PRIMARY KEY(OWNER, CONSTRAINT_NAME)
)
/

CREATE TABLE UTL$DISABLED_CONSTRAINTS (
   OWNER              VARCHAR2(30) NOT NULL,
   TABLE_NAME         VARCHAR2(30) NOT NULL,
   CONSTRAINT_NAME    VARCHAR2(30) NOT NULL
)
/
    
Rem Sequences for utlpurge script

CREATE SEQUENCE SEQ_UTL$LIST_TREE_NODES
/

CREATE SEQUENCE SEQ_UTL$LOG
/

CREATE SEQUENCE SEQ_UTL$SQL
/



Rem Tables for utlmail script

CREATE TABLE UTL$MAIL_INFO (
  MAILHOST  VARCHAR2(100) NOT NULL,
  SENDER    VARCHAR2(200) NOT NULL,
  RECIPIENT VARCHAR2(200) NOT NULL )
/




