rem
rem PACKAGE NAME : USER_AUDIT 
rem

CREATE OR REPLACE PACKAGE SYSTEM.USER_AUDIT 
AS

	PROCEDURE AUDIT_USER_LOGIN ( USERNAME VARCHAR2 ); 
END;
/

CREATE OR REPLACE PACKAGE BODY SYSTEM.USER_AUDIT 
AS

	PROCEDURE AUDIT_USER_LOGIN ( USERNAME VARCHAR2 )
	IS
	BEGIN
		INSERT INTO SYSTEM.AUDIT_USER_LOGIN VALUES ( USERNAME , SYSDATE );

		DELETE FROM SYSTEM.AUDIT_USER_LOGIN WHERE LOGIN_TIME < SYSDATE - 60;
	END;
END;
/



rem
rem DB TRIGGER : SYSTEM.AFTER_USER_LOGIN
rem

CREATE OR REPLACE TRIGGER SYSTEM.AFTER_USER_LOGIN AFTER LOGON ON DATABASE
DECLARE
BEGIN

--        IF SYS_CONTEXT('userenv','session_user') NOT IN ( 'CRONTAB','SYSMAN','DBSNMP','WHITNEY','IPS_REPORT','READONLY' ) THEN

                USER_AUDIT.AUDIT_USER_LOGIN ( SYS_CONTEXT('userenv','session_user' ));

--        END IF;

END;
/

