alter session set current_schema=FIS;
rem alter session set optimizer_index_caching=100;
rem alter session set optimizer_index_cost_adj=1;


rem SELECT  /*+ opt_param('optimizer_index_caching',100) opt_param('optimizer_index_cost_adj',1) */ DISTINCT IDFUND, IDACCOUNT, IDKTOG, 
explain plan for
SELECT DISTINCT IDFUND, IDACCOUNT, IDKTOG, 
       FIRST_VALUE (UDLEVELGROUP) 
       OVER (PARTITION BY IDFUND, IDACCOUNT, IDKTOG ORDER BY PRIORITY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LEVELGROUP 
  FROM (SELECT B.IDFUND, B.IDACCOUNT, KTOG.IDKTOG, GLM.UDLEVELGROUP, FH.PRIORITY 
          FROM (SELECT DISTINCT IDFO IDFUND, IDKTO IDACCOUNT 
                  FROM FIS.FV_KTO_STAND 
                 UNION SELECT DISTINCT IDFO IDFUND, IDKTO IDACCOUNT 
                  FROM FIS.FV_KTO_TRANS 
                 UNION SELECT DISTINCT TRX.IDFO IDFUND, KPL.IDKTO IDACCOUNT 
                  FROM FIS.FV_KTO_TRANS TRX JOIN FIS.FVB_KTO_PLAN KPL ON KPL.UDKTO = TRX.UDGEGENKTO 
               ) B 
               JOIN DVSWEB.VWM_AIS_FUND_HIERARCHY_MATRIX FH ON FH.IDFUND = B.IDFUND 
               JOIN FIS.FMT_KTOGOFKTO KTOG ON KTOG.IDKTO = B.IDACCOUNT 
               JOIN FIS.FV_KTOG_SCHEMA KGS ON KTOG.IDKGS = KGS.IDKGS 
               JOIN FIS.CUST_FVB_GLMAPPING GLM ON GLM.IDKTOG = KTOG.IDKTOG AND FH.LEVELGROUP = GLM.UDLEVELGROUP 
 WHERE GLM.ISDELETED = 'N' 
   AND UDKGS = 'COA_ACCOUNTNUMBER')
/

