alter session set current_schema=MAN;

explain plan for
MERGE INTO HIST_OVERSEC X 
USING ( SELECT *
          FROM (SELECT UDAS, DATESEC, GRPLEVEL, REVISION, IS_VALID, 
                       DECODE(RANK() OVER (PARTITION BY UDAS,DATESEC,GRPLEVEL ORDER BY UDAS, DATESEC,GRPLEVEL, REVISION DESC),1,1,0) AS IS_VALID_NEW 
                  FROM HIST_OVERSEC)
          WHERE NVL(IS_VALID,-1) != IS_VALID_NEW
             OR IS_VALID IS NULL) S0 
ON (X.UDAS = S0.UDAS AND X.DATESEC = S0.DATESEC AND X.GRPLEVEL = S0.GRPLEVEL AND X.REVISION = S0.REVISION)
WHEN MATCHED THEN 
   UPDATE SET IS_VALID = S0.IS_VALID_NEW 
/

