#!/usr/bin/env perl
#
use strict;
use lib '/home/app/oracle/admin/DBA/lib';

use Util::UTIL;
use Db::CONFIG;
use Db::DATABASE;


main();


sub main {
    SendAuditReport();

}

# -------------------------------------------------------------------------------
# Name   : SendAuditReport
# Purpose: 1. Generate Audit_Trail report from the database and sent it to the recipents
#          2. Purge 60 days or older records from sys.aud$ table
# Return : N/A
# -------------------------------------------------------------------------------
sub SendAuditReport {

    my $payload = '';
    my $subject = '';

    my @databases = Db::CONFIG::getDbList();


    foreach my $dbname ( @databases ) {

        next if (Util::UTIL::isMonitor( $dbname ) =~ /NO/i);


        my $config = new Db::CONFIG   ( $dbname );


        if ( $config->isStandby() =~ /yes/i ||                 # Do nothing
             $config->isAsm()     =~ /yes/i ||                 # if it's Standby or ASM or Container 
             $config->getDbType() =~ /CONTAINER/i  ) {
            next;
        }

        my $dh     = new Db::DATABASE ( $dbname );

        # 2017/01/04 - consolidated 11g and 12c version of the scripts.
        @_ = $dh->runSQL2( $config->getSysUser(), "$ENV{ORACLE_BASE}/admin/DBA/crontab/scripts/sql/audit_trail_report.sql" );
        @_ = grep { /\w+/ } @_;

        
        if ( @_ > 0 ) {

            open AUDIT_LOG, ">/tmp/audit_$dbname.log.csv" or die $!;

            print AUDIT_LOG "TIMESTAMP,OS_USERINFO,ATTEMPTED_DB_USER,ACTION,OBJECT_NAME,RETURN CODE,COMMENT\n";

            foreach(@_) {
                my ($timestamp,$os_username,$username,$action_name,$obj_name,$returncode,$comment_text) = split(/,/, $_ );
                print AUDIT_LOG "$timestamp,$os_username,$username,$action_name,$obj_name,$returncode,$comment_text";
 
            }

            close AUDIT_LOG;
        } 

        $subject = "Audit Report - Database Login Attempts ( ";
        $subject .= $dbname . " ) - " . Util::UTIL::getDateStr();

        if ( -f "/tmp/audit_$dbname.log.csv" ) {

            system("$ENV{ORACLE_HOME}/bin/zip /tmp/audit_$dbname.log.csv.zip /tmp/audit_$dbname.log.csv > /dev/null");

#            if ( $dbname =~ /WMXPROD/ ) {
#                Util::UTIL::send_mail( 'WMX-COMPLIANCE' , $subject , "Please review the attached audit_log.csv", "/tmp/audit_$dbname.log.csv.zip");
#            } elsif ( $dbname =~ /MISTPROD/ ) {
#                Util::UTIL::send_mail( 'MIST-COMPLIANCE' , $subject , "Please review the attached audit_log.csv", "/tmp/audit_$dbname.log.csv.zip");
#            } else {
#                Util::UTIL::send_mail( 'COMPLIANCE' , $subject , "Please review the attached audit_log.csv", "/tmp/audit_$dbname.log.csv.zip");
#            }
#
#            system("/bin/rm /tmp/audit_$dbname.log.csv*");
            system("/bin/rm /tmp/audit_$dbname.log.csv");
        }
#        else {
#
#            if ( $dbname =~ /WMXPROD/ ) {
#                Util::UTIL::send_mail( 'WMX-COMPLIANCE' , $subject , "No audit log entry found.");
#            } elsif ( $dbname =~ /MISTPROD/ ) {
#                Util::UTIL::send_mail( 'MIST-COMPLIANCE' , $subject , "No audit log entry found.");
#            } else {
#                Util::UTIL::send_mail( 'COMPLIANCE' , $subject , "No audit log entry found.");
#            }
#
#        }  

    }

}
