#!/usr/bin/perl
# 
use strict;

use lib '/home/app/oracle/admin/DBA/lib';
#use DBI;
use Util::UTIL;
use Db::CONFIG;
use Db::DATABASE;

main();

sub main {

        index_usage();
}



sub index_usage {

    my @listDatabases = Db::CONFIG::getDbList();

 
    foreach my $dbname ( @listDatabases ) {

        next if (Util::UTIL::isMonitor( $dbname ) =~ /NO/i);

        my $config = new Db::CONFIG( $dbname );

        if ( $config->isStandby() =~ /yes/i || $config->isAsm() =~ /yes/i ) {   # Do nothing
            next;                                                               # if it's Standby or ASM
        }


        my $dh = new Db::DATABASE( $dbname );
        $_  = $dh->runSQL2( "$ENV{ORACLE_BASE}/admin/DBA/crontab/scripts/sql/index_usage.sql" );
        
    }
}


