SET PAGESIZE 0
SET LINESIZE 180
SET ECHO ON
SET SERVEROUT ON
SET TIMING ON

spool &1/log/gather_database_stats.log

begin
    -- DBMS_SCHEDULER.RUN_JOB('GATHER_DATABASE_STATS');

    DBMS_STATS.GATHER_DATABASE_STATS(
    ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,
    METHOD_OPT => 'FOR ALL COLUMNS SIZE AUTO',
    CASCADE => TRUE,
    DEGREE => 24);
end;
/

spool off

exit
