spool WEEKLY_PURGE_1027

whenever sqlerror exit rollback

declare
  l_dummy number;
begin
  select 1 
  into l_dummy
  from whitney.schema_version
  where branch = '10.2.7';
end;
/

SET TIMING ON
SET ECHO ON

WHENEVER SQLERROR CONTINUE

SET HEADING OFF

SELECT 'Purge started at                   : '||SYSTIMESTAMP FROM DUAL;

SET HEADING ON

/*
 * PURGE ORDER_HISTORY
 */
    DELETE WHITNEY.ORDER_HISTORY WHERE EVENT_DATE_TIME < ADD_MONTHS(SYSDATE, -6);

    COMMIT;

/*
 * PURGE AUDIT_LOG
 */
    DELETE WHITNEY.AUDIT_LOG WHERE DATE_TIME < ADD_MONTHS(SYSDATE, -6);

    COMMIT;

/*
 * PURGE JOURNAL_ENTRY
 */

    DELETE WHITNEY.JOURNAL_ENTRY WHERE EFFECTIVE_DATE < ADD_MONTHS(SYSDATE, -6);

    COMMIT;

/*
 * PURGE BR_ACCOUNT_BALANCE
 */

    DELETE WHITNEY.BR_ACCOUNT_BALANCE WHERE POST_DATE < ADD_MONTHS(SYSDATE, -6);

    COMMIT;

/*
 * PURGE TRADES
 */


    INSERT INTO WHITNEY.TERMINATED_TRADE_KEY(TRADE_KEY)
    SELECT trade_key from whitney.trade 
    WHERE TRADE_DATE < ADD_MONTHS(SYSDATE, -6);
     
    INSERT  INTO WHITNEY.TERMINATED_TRADE_KEY(TRADE_KEY) 
    SELECT  aggregate_trade_key FROM WHITNEY.trade_link WHERE single_trade_key in (select trade_key from WHITNEY.terminated_trade_key);

    INSERT  INTO WHITNEY.TERMINATED_TRADE_KEY(TRADE_KEY) 
    SELECT  single_trade_key FROM  WHITNEY.TRADE_LINK WHERE aggregate_trade_key in (select trade_key from WHITNEY.terminated_trade_key);  
    
    UPDATE WHITNEY.TRADE 
       SET PARENT_TRADE_KEY = ''
     WHERE PARENT_TRADE_KEY IS NOT NULL 
       AND PARENT_TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    UPDATE WHITNEY.TRADE 
       SET HUB_TRADE_KEY = NULL 
     WHERE HUB_TRADE_KEY IS NOT NULL AND HUB_TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.STP_EVENT 
     WHERE TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.TRADE_BLOCK_ITEM_DF WHERE TRADE_BLOCK_ITEM_KEY IN 
    (SELECT TRADE_BLOCK_ITEM_KEY FROM WHITNEY.TRADE_BLOCK_ITEM WHERE TRADE_BLOCK_KEY IN
    (SELECT trade_block_key FROM whitney.trade_block WHERE trade_key IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));

    DELETE  WHITNEY.TRADE_BLOCK_ITEM_DF WHERE TRADE_BLOCK_ITEM_KEY IN 
    (SELECT TRADE_BLOCK_ITEM_KEY FROM WHITNEY.TRADE_BLOCK_ITEM WHERE TRADE_BLOCK_KEY IN
    (SELECT trade_block_key FROM whitney.trade_block WHERE trade_key IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));

    DELETE  WHITNEY.TRADE_BLOCK_ITEM WHERE TRADE_BLOCK_KEY IN
    (SELECT trade_block_key FROM whitney.trade_block WHERE trade_key IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY));

    DELETE  WHITNEY.TRADE_BLOCK WHERE TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.TRADE_LINK WHERE SINGLE_TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.TRADE_LINK WHERE AGGREGATE_TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.TRADE_PAYMENT WHERE trade_key IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);
    
    DELETE  WHITNEY.TRADE_TRANSITION WHERE trade_key IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  WHITNEY.TRADE_DEFINED_FIELD WHERE TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);
        
    DELETE WHITNEY.TRADE_PAYMENT WHERE TRADE_KEY IN 
    (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY WHERE TRADE_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TRADE_PAYMENT));

    COMMIT;

    DELETE FROM WHITNEY.TRADE T 
    WHERE EXISTS 
    (SELECT 1 
    FROM WHITNEY.TERMINATED_TRADE_KEY TT
    WHERE TT.TRADE_KEY=T.TRADE_KEY);

    DELETE FROM WHITNEY.TERMINATED_TRADE_KEY;

    COMMIT;


/*
 * PURGE DRAFTS
 */

    INSERT INTO WHITNEY.TERMINATED_TRADE_KEY (TRADE_KEY) 
    SELECT TRADE_REQUEST_KEY FROM WHITNEY.TRADE_REQUEST WHERE LAST_UPDATED_DATE < ADD_MONTHS(SYSDATE, -6);

    DELETE WHITNEY.MISSED_OPPORTUNITY WHERE PRICING_ROUND_KEY IN 
    (SELECT PRICING_ROUND_KEY FROM WHITNEY.PRICING_ROUND WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.TRADE_REQUEST WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));
    
    DELETE WHITNEY.PRICE_INPUT_BANK_LIST WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.PRICING_INPUT WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY));
   
    DELETE WHITNEY.QUOTE WHERE PRICING_ROUND_KEY IN 
    (SELECT PRICING_ROUND_KEY FROM WHITNEY.PRICING_ROUND WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.TRADE_REQUEST WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));
    
    DELETE WHITNEY.ORDER_TRANSITION WHERE PRICING_ROUND_KEY IN 
    (SELECT PRICING_ROUND_KEY FROM WHITNEY.PRICING_ROUND WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.TRADE_REQUEST WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));

    UPDATE WHITNEY.TRADE 
       SET PRICING_ROUND_KEY = NULL 
     WHERE PRICING_ROUND_KEY IN (SELECT PRICING_ROUND_KEY FROM WHITNEY.PRICING_ROUND WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.PRICING_INPUT WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));

    DELETE  FROM WHITNEY.PRICING_ROUND WHERE PRICING_INPUT_KEY IN 
    (SELECT PRICING_INPUT_KEY FROM WHITNEY.PRICING_INPUT WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY));

    DELETE  FROM WHITNEY.PRICING_INPUT WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE WHITNEY.TRADE_REQUEST_DF WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE WHITNEY.TRADE_BLOCK_ITEM_DF WHERE TRADE_BLOCK_ITEM_KEY IN 
    (SELECT TRADE_BLOCK_ITEM_KEY FROM  WHITNEY.TRADE_BLOCK_ITEM WHERE TRADE_BLOCK_KEY IN
    (SELECT TRADE_BLOCK_KEY FROM WHITNEY.TRADE_BLOCK WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY)));

    DELETE WHITNEY.TRADE_BLOCK_ITEM WHERE TRADE_BLOCK_KEY IN
    (SELECT TRADE_BLOCK_KEY FROM WHITNEY.TRADE_BLOCK WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY));

    DELETE WHITNEY.TRADE_BLOCK WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    DELETE  FROM WHITNEY.TRADE_REQUEST WHERE TRADE_REQUEST_KEY IN (SELECT TRADE_KEY FROM WHITNEY.TERMINATED_TRADE_KEY);

    COMMIT;


/*
 * PURGE MARGIN_POSITION_TRANS
 */

    DELETE WHITNEY.MARGIN_CLOSING_TRADE
    WHERE OPN_POSITION_TRANS_KEY IN
    ( SELECT MARGIN_POSITION_TRANS_KEY
        FROM WHITNEY.MARGIN_POSITION_TRANS
       WHERE DATE_TIME < ADD_MONTHS(SYSDATE, -6)+1);

    DELETE WHITNEY.MARGIN_CLOSING_TRADE
    WHERE CLS_POSITION_TRANS_KEY IN
    ( SELECT MARGIN_POSITION_TRANS_KEY
        FROM WHITNEY.MARGIN_POSITION_TRANS
       WHERE DATE_TIME < ADD_MONTHS(SYSDATE, -6) +1);

    DELETE WHITNEY.MARGIN_POSITION_TRANS
    WHERE DATE_TIME < ADD_MONTHS(SYSDATE, -6);

    COMMIT;



-- UPDATE TRADE_REQUEST

    UPDATE WHITNEY.TRADE_REQUEST
    SET IS_AVAILABLE = 'N'
    WHERE IS_AVAILABLE = 'Y'
    AND TRADE_REQUEST_KEY IN
    (
      SELECT TRADE_REQUEST_KEY
      FROM WHITNEY.PRICING_INPUT
      WHERE PRICING_TYPE = 'ORDER'
      AND PRICING_INPUT_KEY IN
        (
          SELECT PRICING_INPUT_KEY
          FROM WHITNEY.PRICING_ROUND
          WHERE PRICING_ROUND_KEY NOT IN
            (
              SELECT PRICING_ROUND_KEY
              FROM WHITNEY.TRADE
            )
         )
    );

-- UPDATE ESP ORDERS
 
    UPDATE WHITNEY.PRICING_INPUT
    SET IS_ACTIVE = 'N',
        PRICING_INPUT_STATUS = 'CANCELLED',
        CANCEL_DATE = SYSDATE
    WHERE PRICING_TYPE = 'ESP_ORDER'
    AND IS_ACTIVE='Y'
    AND PRICING_INPUT_KEY IN
    (
      SELECT PRICING_INPUT_KEY
      FROM WHITNEY.PRICING_ROUND
      WHERE PRICING_ROUND_KEY NOT IN
        (
          SELECT PRICING_ROUND_KEY
          FROM WHITNEY.TRADE
        )
    );

-- UPDATE REQUESTS

    UPDATE WHITNEY.PRICING_INPUT
    SET IS_AVAILABLE = 'N'
    WHERE IS_AVAILABLE = 'Y'
    AND PRICING_TYPE = 'REQUEST'
    AND PRICING_INPUT_KEY IN
      (
        SELECT PRICING_INPUT_KEY
        FROM WHITNEY.PRICING_ROUND
        WHERE PRICING_ROUND_KEY NOT IN
        (
          SELECT PRICING_ROUND_KEY
          FROM WHITNEY.TRADE
        )
      );

-- UPDATE COMPLEX_ORDER

    UPDATE WHITNEY.COMPLEX_ORDER 
    SET COMPLEX_ORDER_STATUS = 'CANCELLED'
    WHERE COMPLEX_ORDER_STATUS != 'CANCELLED'
    AND COMPLEX_ORDER_KEY IN 
      (
        SELECT COMPLEX_ORDER_KEY 
        FROM WHITNEY.CO_TRADE_LINK 
        WHERE TRADE_ID NOT IN
          (
            SELECT TRADE_ID 
            FROM WHITNEY.TRADE
          )
      );

    COMMIT;

-- Automatically disable drafts older than one month using script below --DEMO-792, UAT-666

    UPDATE WHITNEY.PRICING_INPUT
    SET IS_AVAILABLE ='N',
    IS_ACTIVE ='N',
    PRICING_INPUT_STATUS= 'CANCELLED', 
    LAST_UPDATED_BY='Draft Disabling Script', 
    LAST_UPDATED_DATE=SYSDATE
    WHERE TRADE_REQUEST_KEY IN 
    (
       SELECT TRADE_REQUEST_KEY 
       FROM WHITNEY.TRADE_REQUEST
       WHERE DEFINE_DATE <ADD_MONTHS(SYSDATE, -1)
       AND IS_AVAILABLE ='Y'
       AND IS_TEMPLATE='N'
    );


    UPDATE WHITNEY.TRADE_REQUEST
    SET IS_AVAILABLE ='N',
    LAST_UPDATED_BY='Draft Disabling Script', 
    LAST_UPDATED_DATE=SYSDATE
    WHERE DEFINE_DATE < ADD_MONTHS(SYSDATE, -1)
    AND IS_AVAILABLE ='Y'
    AND IS_TEMPLATE='N';
    
    COMMIT;


SET HEADING OFF

SELECT 'Purge finished at                   : '||SYSTIMESTAMP FROM DUAL;

spool off

exit;
