SPO coe_xfr_sql_profile_2kmf3av4jqmgt_3521757961.log;
SET ECHO ON TERM ON LIN 2000 TRIMS ON NUMF 99999999999999999999;
REM
REM $Header: 215187.1 coe_xfr_sql_profile_2kmf3av4jqmgt_3521757961.sql 11.4.4.4 2020/11/17 carlos.sierra $
REM
REM Copyright (c) 2000-2012, Oracle Corporation. All rights reserved.
REM
REM AUTHOR
REM   carlos.sierra@oracle.com
REM
REM SCRIPT
REM   coe_xfr_sql_profile_2kmf3av4jqmgt_3521757961.sql
REM
REM DESCRIPTION
REM   This script is generated by coe_xfr_sql_profile.sql
REM   It contains the SQL*Plus commands to create a custom
REM   SQL Profile for SQL_ID 2kmf3av4jqmgt based on plan hash
REM   value 3521757961.
REM   The custom SQL Profile to be created by this script
REM   will affect plans for SQL commands with signature
REM   matching the one for SQL Text below.
REM   Review SQL Text and adjust accordingly.
REM
REM PARAMETERS
REM   None.
REM
REM EXAMPLE
REM   SQL> START coe_xfr_sql_profile_2kmf3av4jqmgt_3521757961.sql;
REM
REM NOTES
REM   1. Should be run as SYSTEM or SYSDBA.
REM   2. User must have CREATE ANY SQL PROFILE privilege.
REM   3. SOURCE and TARGET systems can be the same or similar.
REM   4. To drop this custom SQL Profile after it has been created:
REM      EXEC DBMS_SQLTUNE.DROP_SQL_PROFILE('coe_2kmf3av4jqmgt_3521757961');
REM   5. Be aware that using DBMS_SQLTUNE requires a license
REM      for the Oracle Tuning Pack.
REM   6. If you modified a SQL putting Hints in order to produce a desired
REM      Plan, you can remove the artifical Hints from SQL Text pieces below.
REM      By doing so you can create a custom SQL Profile for the original
REM      SQL but with the Plan captured from the modified SQL (with Hints).
REM
WHENEVER SQLERROR EXIT SQL.SQLCODE;
REM
VAR signature NUMBER;
VAR signaturef NUMBER;
REM
DECLARE
sql_txt CLOB;
h       SYS.SQLPROF_ATTR;
PROCEDURE wa (p_line IN VARCHAR2) IS
BEGIN
DBMS_LOB.WRITEAPPEND(sql_txt, LENGTH(p_line), p_line);
END wa;
BEGIN
DBMS_LOB.CREATETEMPORARY(sql_txt, TRUE);
DBMS_LOB.OPEN(sql_txt, DBMS_LOB.LOB_READWRITE);
-- SQL Text pieces below do not have to be of same length.
-- So if you edit SQL Text (i.e. removing temporary Hints),
-- there is no need to edit or re-align unmodified pieces.
wa(q'[SELECT INPUT_DESC, INPUT_VALUE, INPUT_TYPE, INPUT_SEQ, TRADE_TO_]');
wa(q'[TARGET
                                            FROM PLUGIN_T]');
wa(q'[RACK, ACCOUNTS_ALL 
                                            ]');
wa(q'[WHERE ACCOUNTS_ALL.NAME = :accountName 
                        ]');
wa(q'[                    AND PLUGIN_NAME = :pluginName 
             ]');
wa(q'[                               AND MODULE = :model 
            ]');
wa(q'[                                AND PLUGIN_TRACK.ACCOUNT_ID = AC]');
wa(q'[COUNTS_ALL.ID 
                                            AND I]');
wa(q'[S_EXPIRED = 0 
                                            AND (]');
wa(q'[(CAST(DATE_UPDATED AS DATE) - (SELECT CAST(MAX(DATE_UPDATED) AS ]');
wa(q'[DATE) 
                                            FROM PLUGIN_T]');
wa(q'[RACK, ACCOUNTS_ALL 
                                            ]');
wa(q'[WHERE ACCOUNTS_ALL.NAME = :accountName 
                        ]');
wa(q'[                    AND PLUGIN_NAME = :pluginName 
             ]');
wa(q'[                               AND MODULE = :model 
            ]');
wa(q'[                                AND PLUGIN_TRACK.ACCOUNT_ID = AC]');
wa(q'[COUNTS_ALL.ID 
                                            AND I]');
wa(q'[S_EXPIRED = 0)) * 24 * 60 >= -5) 
                              ]');
wa(q'[              ORDER BY PLUGIN_TRACK.ACCOUNT_ID, PLUGIN_TRACK.PLU]');
wa(q'[GIN_NAME, PLUGIN_TRACK.DATE_UPDATED DESC, PLUGIN_TRACK.INPUT_SEQ]');
wa(q'[ DESC]');
DBMS_LOB.CLOSE(sql_txt);
h := SYS.SQLPROF_ATTR(
q'[BEGIN_OUTLINE_DATA]',
q'[IGNORE_OPTIM_EMBEDDED_HINTS]',
q'[OPTIMIZER_FEATURES_ENABLE('11.2.0.3')]',
q'[DB_VERSION('12.1.0.2')]',
q'[OPT_PARAM('optimizer_index_cost_adj' 20)]',
q'[OPT_PARAM('optimizer_index_caching' 80)]',
q'[ALL_ROWS]',
q'[OUTLINE_LEAF(@"SEL$2")]',
q'[OUTLINE_LEAF(@"SEL$1")]',
q'[FULL(@"SEL$1" "ACCOUNTS_ALL"@"SEL$1")]',
q'[INDEX(@"SEL$1" "PLUGIN_TRACK"@"SEL$1" ("PLUGIN_TRACK"."PLUGIN_NAME" "PLUGIN_TRACK"."MODULE" "PLUGIN_TRACK"."ACCOUNT_ID"))]',
q'[LEADING(@"SEL$1" "ACCOUNTS_ALL"@"SEL$1" "PLUGIN_TRACK"@"SEL$1")]',
q'[USE_NL(@"SEL$1" "PLUGIN_TRACK"@"SEL$1")]',
q'[NLJ_BATCHING(@"SEL$1" "PLUGIN_TRACK"@"SEL$1")]',
q'[PUSH_SUBQ(@"SEL$2")]',
q'[FULL(@"SEL$2" "ACCOUNTS_ALL"@"SEL$2")]',
q'[INDEX(@"SEL$2" "PLUGIN_TRACK"@"SEL$2" ("PLUGIN_TRACK"."PLUGIN_NAME" "PLUGIN_TRACK"."MODULE" "PLUGIN_TRACK"."ACCOUNT_ID"))]',
q'[LEADING(@"SEL$2" "ACCOUNTS_ALL"@"SEL$2" "PLUGIN_TRACK"@"SEL$2")]',
q'[USE_NL(@"SEL$2" "PLUGIN_TRACK"@"SEL$2")]',
q'[NLJ_BATCHING(@"SEL$2" "PLUGIN_TRACK"@"SEL$2")]',
q'[END_OUTLINE_DATA]');
:signature := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt);
:signaturef := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt, TRUE);
DBMS_SQLTUNE.IMPORT_SQL_PROFILE (
sql_text    => sql_txt,
profile     => h,
name        => 'coe_2kmf3av4jqmgt_3521757961',
description => 'coe 2kmf3av4jqmgt 3521757961 '||:signature||' '||:signaturef||'',
category    => 'DEFAULT',
validate    => TRUE,
replace     => TRUE,
force_match => FALSE /* TRUE:FORCE (match even when different literals in SQL). FALSE:EXACT (similar to CURSOR_SHARING) */ );
DBMS_LOB.FREETEMPORARY(sql_txt);
END;
/
WHENEVER SQLERROR CONTINUE
SET ECHO OFF;
PRINT signature
PRINT signaturef
PRO
PRO ... manual custom SQL Profile has been created
PRO
SET TERM ON ECHO OFF LIN 80 TRIMS OFF NUMF "";
SPO OFF;
PRO
PRO COE_XFR_SQL_PROFILE_2kmf3av4jqmgt_3521757961 completed
